version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8182"
    volumes:
      - .:/code
    restart: always
    # env_file:
    #   - .env
    # depends_on:
    #   - db
    networks:
      - frontend

networks:
  frontend: