version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8001"
    volumes:
      - .:/code
    # env_file:
    #   - .env
    # depends_on:
    #   - db
    networks:
      - frontend

networks:
  frontend: